### ISSUE TITLE
Feedback HW4

### ISSUE THREAD

**Issue by Kashoid23** [VladFomenko/RubyHW#13]
- [x] Перейменуйте метод таким чином щоб він відповідав результату (передавав зміст роботи)
```
def request(path)
  Rack::Response.new(render(path)).finish
end
```
- [x] Прочитайте https://blog.appsignal.com/2018/09/11/differences-between-nil-empty-blank-and-present.html Використайте замість `value.nil? || value.empty?` більш підходящий метод, за потреби оновіть умови.

- [x] Прочитайте https://www.rubyguides.com/2018/11/attr_accessor/ та використайте attr_reader. Також це дасть вам можливість звертатись до ваших атрибутів в методах екземпляру напряму `name` замість `@name`

- [x] Ніколи не пуште закоментований код, якщо це не коментарі з поясненням коду, або TODO
`# request('end.html.erb') if @message.include?('died')`

- [x] Прочитайте https://www.rubyinrails.com/2014/01/03/ruby-difference-between-single-and-double-quotes/ та оновіть код

- [x] Використайте partial https://guides.rubyonrails.org/layouts_and_rendering.html#using-partials, щоб не дублювати тег head в трьох views. Приклад я вже давав, коли розповідав про Rack
```
<head>
  <title>Tamagotchi</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
```

**Comment by VladFomenko** [comment]
I did. The methods blank? and present? for only rails.

**Comment by Kashoid23** [comment]
@VladFomenko
`The methods blank? and present? for only rails.` це не зовсім так.

Зараз він вшитий в rails, але це частина гема active_support, їх можна зареквайрити
`require 'active_support/core_ext/object/blank'`
 
Ну, або чистим Ruby 😆 
`!!value&.length&.positive?`

**Comment by VladFomenko** [comment]
Окей) гляну! Зараз займаюсь шостою домашкою, як зроблю то пограюсь з цим. Дякую!

**Comment by Kashoid23** [comment]
В цілому гарна робота )
Закриваю ішюс, якщо буде бажання спробуй `active_support/core_ext/object/blank` ) Не хочу щоб ти обмежував свої уявлення, типу ми чогось не можемо ) Рубі універсальні )
